export const PRESET_SCHEMA_VERSION = 2;

const style = (value) => Object.freeze(value);

export const STYLES = Object.freeze({
  "marshmallow-clay": style({
    nameZh: "棉花糖软陶", nameEn: "Marshmallow Clay", summaryZh: "圆润蓬松、低饱和的 Q 版软陶图标",
    material: "matte polymer clay with a fine, velvety surface",
    surface: "powder-soft finish, no gloss except tiny eye highlights",
    geometry: "inflated rounded masses with seamless joins and no sharp corners",
    proportions: "chibi proportions, oversized defining feature, compact body, short supporting parts",
    camera: "consistent three-quarter view from slightly above, about 30 degrees",
    composition: "one centered object, 72-78% of the square canvas, generous even breathing room",
    lighting: "large softbox from upper left with gentle ambient fill",
    shadow: "small soft contact shadow directly beneath the object",
    edges: "clean silhouette without a drawn contour",
    detailDensity: "low; preserve two to four identity-defining details only",
    background: "plain warm near-white studio background",
    colorBehavior: "use broad pastel color blocks with one small saturated accent",
    consistency: "keep identical camera angle, clay grain, corner radius, scale, light direction, and shadow softness across the set",
    bestFor: "friendly apps, onboarding, education, wellness, family products",
    avoid: "hard bevels, thin fragile parts, glossy plastic, realistic pores, deep creases, black outlines",
  }),
  "macaron-mascot": style({
    nameZh: "马卡龙萌物", nameEn: "Macaron Mascot", summaryZh: "有表情、有性格的卡通马卡龙 Q 版图标",
    material: "smooth matte toy resin with a soft-touch coating",
    surface: "clean satin-matte finish with restrained highlights",
    geometry: "simple rounded toy forms built from spheres, capsules, and soft wedges",
    proportions: "very cute chibi ratio; large head or main symbol, tiny limbs, compact stance",
    camera: "front three-quarter product view at eye level",
    composition: "single mascot-like object centered at 74% canvas height; facial features remain readable at 64 px",
    lighting: "bright diffused studio light with a delicate rim fill",
    shadow: "short blurred grounding shadow, never floating",
    edges: "crisp silhouette with no heavy contour; use a colored edge only for facial clarity",
    detailDensity: "medium-low; one face, one signature prop, and minimal decoration",
    background: "solid milk-white background without scenery",
    colorBehavior: "macaron body colors, dark warm facial details, one candy-bright focal accent",
    consistency: "keep the same eye style, cheek treatment, limb thickness, head-to-body ratio, camera, and baseline",
    bestFor: "community, lifestyle, children, creator tools, playful product navigation",
    avoid: "uncanny realism, detailed fingers, complex costumes, large open mouths, busy patterns, text labels",
  }),
  "frosted-gummy": style({
    nameZh: "糖霜软糖", nameEn: "Frosted Gummy", summaryZh: "半透明软糖与糖霜高光结合的甜感图标",
    material: "translucent gummy gel with a lightly frosted outer skin",
    surface: "soft subsurface glow, controlled glossy highlight, no wet look",
    geometry: "thick rounded silhouettes with softly compressed bases",
    proportions: "compact and chunky with no element thinner than one tenth of the main body",
    camera: "near-front three-quarter view, consistent 35 mm product lens",
    composition: "one bold silhouette filling 70-76% of canvas with no overlaps at the border",
    lighting: "broad back-side glow plus soft frontal fill to reveal translucency",
    shadow: "colored translucent contact shadow with low opacity",
    edges: "smooth refractive edge, no outline",
    detailDensity: "low; use embedded color shapes rather than tiny surface marks",
    background: "clean very pale neutral background",
    colorBehavior: "one dominant translucent hue, one contrasting core color, neutral highlight",
    consistency: "match transparency, wall thickness, highlight size, camera, and internal color saturation",
    bestFor: "music, entertainment, rewards, social reactions, seasonal campaigns",
    avoid: "glass sharpness, liquid drips, excessive reflections, bubbles everywhere, realistic candy branding",
  }),
  "stitched-fiber": style({
    nameZh: "缝线纤维板", nameEn: "Stitched Fiberboard", summaryZh: "带切边、层厚和缝线细节的手作纸板图标",
    material: "layered recycled fiberboard, colored craft paper, cotton cord, and small paper fasteners",
    surface: "visible fine paper fibers and subtle natural variation, never dirty",
    geometry: "assembled miniature objects with believable folded planes, slots, tabs, and layered cut pieces",
    proportions: "toy-like but structurally plausible, sturdy parts and slightly oversized connectors",
    camera: "consistent three-quarter view from slightly above",
    composition: "single handcrafted object centered, 68-75% canvas coverage, stable grounded base",
    lighting: "soft daylight studio lighting that reveals edge thickness and texture",
    shadow: "natural soft contact shadow with slight ambient occlusion at joints",
    edges: "visible clean cut edges, selective rounded corners, decorative stitching only where construction supports it",
    detailDensity: "medium-high; fibers, seams, folds, and fasteners are readable but not noisy",
    background: "plain warm white seamless backdrop",
    colorBehavior: "kraft neutral as the material anchor plus three assigned paper colors",
    consistency: "match board thickness, fiber scale, stitch length, connector size, camera, and construction logic",
    bestFor: "commerce, logistics, sustainability, handmade brands, educational sets",
    avoid: "brand packaging, printed words, torn dirty edges, impossible floating layers, plastic gloss, metal-heavy construction",
  }),
  "ink-accent": style({
    nameZh: "墨线跳色", nameEn: "Ink Accent", summaryZh: "白色主体、统一墨线与少量高亮色的产品图标",
    material: "clean vector-like illustration with subtle dimensional fills",
    surface: "mostly flat white surfaces with restrained pale cool-gray side planes",
    geometry: "recognizable simplified objects with mildly rounded corners",
    proportions: "balanced product-icon proportions with one dominant readable silhouette",
    camera: "mostly front-facing with a consistent slight three-quarter turn where depth is needed",
    composition: "one centered object, 68-74% canvas coverage, aligned to a common optical baseline",
    lighting: "minimal implied top-left light rather than rendered studio highlights",
    shadow: "tiny pale-gray offset or base shadow only",
    edges: "uniform warm-black contour, rounded joins and caps, identical apparent stroke weight",
    detailDensity: "medium; enough internal lines to identify the object, never technical illustration density",
    background: "pure or near-white flat background",
    colorBehavior: "white dominant body, one vivid primary accent, one secondary accent, black structural details",
    consistency: "lock contour weight, corner radius, accent area percentage, perspective depth, baseline, and negative space",
    bestFor: "SaaS navigation, finance, productivity, media, feature grids",
    avoid: "variable line weight, sketchy strokes, gradients, realistic texture, large dark fills, full-color surfaces",
  }),
  "paper-relief": style({
    nameZh: "纸雕浅浮", nameEn: "Paper Relief", summaryZh: "层叠彩纸形成浅浮雕与柔和投影",
    material: "smooth matte art paper in precisely cut stacked layers",
    surface: "uniform paper tooth with no printed noise",
    geometry: "flat cut silhouettes separated into three to five shallow depth layers",
    proportions: "simple iconic shapes with broad bridges between cut regions",
    camera: "orthographic near-front view with a very slight top view",
    composition: "centered emblem filling about 72% of canvas, balanced radial or vertical layering",
    lighting: "soft upper-left light designed to reveal layer separation",
    shadow: "narrow consistent shadows between layers plus a faint overall contact shadow",
    edges: "precise paper cuts with subtly visible thickness, no ink outline",
    detailDensity: "medium-low; prioritize large nested shapes",
    background: "single pale paper sheet distinct from the object palette",
    colorBehavior: "assign one color per depth layer and maintain clear luminance separation",
    consistency: "lock layer count, paper thickness, shadow offset, cut radius, camera, and color ordering",
    bestFor: "editorial categories, culture, travel, nature, calm utilities",
    avoid: "origami folds, torn paper, thick cardboard, photoreal scenery, excessive tiny cutouts, floating scraps",
  }),
  "felt-patch": style({
    nameZh: "毛毡贴布", nameEn: "Felt Patch", summaryZh: "柔软毛毡、贴布层次和短针脚的温暖图标",
    material: "dense wool felt and layered fabric appliqué",
    surface: "soft short fibers with restrained tactile texture",
    geometry: "flat padded patches with rounded cut shapes and shallow overlap",
    proportions: "bold simplified silhouette with thick safe margins around details",
    camera: "front view with a slight top-down angle",
    composition: "single patch centered at 70-76% of canvas, no loose decorative pieces",
    lighting: "broad warm light with soft ambient fill",
    shadow: "very shallow textile contact shadow between layers",
    edges: "soft cut felt edges and evenly spaced short stitches on selected seams",
    detailDensity: "medium-low; texture supports rather than obscures the symbol",
    background: "plain light textile or warm-neutral background",
    colorBehavior: "muted fabric colors with one brighter stitched accent",
    consistency: "match fiber length, felt thickness, stitch spacing, padding, camera, and silhouette complexity",
    bestFor: "learning, journaling, craft, family, cozy lifestyle products",
    avoid: "knitted loops, frayed damage, long loose threads, dense embroidery, realistic clothing scenes",
  }),
  "bubble-sticker": style({
    nameZh: "果冻贴纸", nameEn: "Bubble Sticker", summaryZh: "厚边贴纸、圆润高光和清晰小尺寸轮廓",
    material: "thick domed vinyl sticker with a satin protective coating",
    surface: "smooth controlled highlight with no mirror reflection",
    geometry: "front-facing rounded graphic enclosed by a consistent sticker border",
    proportions: "bold emblem with large interior shapes and minimal cut-ins",
    camera: "straight-on orthographic view",
    composition: "single sticker centered at 74% canvas size with uniform outer border",
    lighting: "soft frontal light plus one small upper-left highlight",
    shadow: "short soft offset shadow showing sticker thickness",
    edges: "uniform cream or white kiss-cut border, smooth contour",
    detailDensity: "low; optimized for recognition at 32-64 px",
    background: "solid contrasting pastel background or transparent-ready plain field",
    colorBehavior: "two main flat colors, one highlight, one dark detail color",
    consistency: "lock border thickness, dome height, highlight placement, shadow offset, scale, and frontal camera",
    bestFor: "reactions, badges, mobile tabs, creator tools, playful controls",
    avoid: "paper grain, peeling corners, multiple stickers, typography, realistic decals, complex internal linework",
  }),
  "mini-diorama": style({
    nameZh: "袖珍场景", nameEn: "Mini Diorama", summaryZh: "在统一底座上讲清功能的小型 Q 版场景",
    material: "matte painted miniature resin and soft polymer clay",
    surface: "clean handcrafted finish with subtle material separation",
    geometry: "one hero object plus at most two supporting props on a compact base",
    proportions: "chibi miniatures with oversized functional features and sturdy shapes",
    camera: "fixed isometric-like three-quarter view from 35 degrees above",
    composition: "contained vignette on the same rounded base, filling 72-78% of canvas",
    lighting: "soft cinematic key from upper left with gentle fill and no dramatic darkness",
    shadow: "grounded ambient occlusion and one unified soft base shadow",
    edges: "clean rounded forms without drawn outlines",
    detailDensity: "medium; props must clarify the function rather than decorate",
    background: "plain pale studio field with no horizon line",
    colorBehavior: "neutral base, dominant subject color, secondary prop color, small focal accent",
    consistency: "lock base shape, camera, object scale, prop count, material finish, lighting, and scene density",
    bestFor: "feature explanations, empty states, workflows, service categories",
    avoid: "full landscapes, more than three subjects, dramatic depth of field, tiny people, text signs, clutter",
  }),
  "chalky-gouache": style({
    nameZh: "粉彩厚涂", nameEn: "Chalky Gouache", summaryZh: "不规则手绘边缘与粉彩厚涂质感的绘本图标",
    material: "opaque gouache paint on smooth cold-press paper",
    surface: "chalky matte paint with subtle dry-brush variation",
    geometry: "simple hand-painted silhouettes with gently imperfect curves",
    proportions: "friendly storybook exaggeration with one clearly dominant form",
    camera: "mostly front view, using only shallow implied depth",
    composition: "single isolated illustration occupying 68-74% of canvas",
    lighting: "painted soft tonal modeling without a photographic light source",
    shadow: "simple colored painted shadow close to the object",
    edges: "soft colored edges with slight brush variation, never a heavy black contour",
    detailDensity: "medium-low; broad brush shapes and a few expressive marks",
    background: "plain off-white paper with extremely subtle grain",
    colorBehavior: "muted pastel base with one warm narrative accent and dark colored details",
    consistency: "match brush scale, edge softness, paint opacity, camera, shadow language, and detail count",
    bestFor: "reading, mindfulness, culture, education, gentle empty states",
    avoid: "watercolor blooms, oil impasto, pencil sketch construction, realistic scenery, typography, noisy paper stains",
  }),
});

export const PALETTES = Object.freeze({
  "macaron-garden": Object.freeze({
    nameZh: "马卡龙花园", nameEn: "Macaron Garden", summaryZh: "粉、黄、薄荷、天蓝组成的柔甜通用色板",
    roles: { primary: "草莓粉 #F4A7BE", secondary: "奶油黄 #F7D889", tertiary: "薄荷绿 #9FD8C0", accent: "晴空蓝 #91BFE3", detail: "暖墨色 #3F3942", background: "牛奶白 #FFF9F5" },
    guidance: "Use primary and secondary for large masses, tertiary for support, accent below 15%, and detail only for facial or structural marks.",
    contrast: "Keep adjacent pastel masses separated by luminance or the warm detail color; do not place yellow details on white.",
  }),
  "soda-shop": Object.freeze({
    nameZh: "汽水糖铺", nameEn: "Soda Shop", summaryZh: "珊瑚、柠檬、蓝莓和葡萄的活泼配色",
    roles: { primary: "珊瑚红 #EF7F8D", secondary: "柠檬黄 #F4D35E", tertiary: "蓝莓蓝 #70A7DD", accent: "葡萄紫 #A88AD6", detail: "深莓黑 #3D3545", background: "清透白 #FFFFFF" },
    guidance: "Choose one dominant candy color per icon; rotate supporting colors across the set while retaining the same role hierarchy.",
    contrast: "Use the dark detail color for small marks; never combine all four chromatic colors in equal area.",
  }),
  "mint-morning": Object.freeze({
    nameZh: "薄荷清晨", nameEn: "Mint Morning", summaryZh: "薄荷、雾蓝、杏色构成的清爽低刺激色板",
    roles: { primary: "清薄荷 #83CDB4", secondary: "雾蓝 #9CBFDB", tertiary: "柔杏 #F2C6A0", accent: "珊瑚粉 #EB8F9D", detail: "青灰 #344D50", background: "晨雾白 #F8FCFA" },
    guidance: "Let mint or mist blue occupy most of the object; reserve coral for the focal action or status.",
    contrast: "Separate mint and blue with the background or detail tone because their luminance is close.",
  }),
  "kraft-play": Object.freeze({
    nameZh: "牛皮纸乐园", nameEn: "Kraft Play", summaryZh: "牛皮纸中性色搭配钴蓝、青绿和橙色",
    roles: { primary: "牛皮纸 #C99B63", secondary: "钴蓝 #4F67B1", tertiary: "青瓷绿 #68A69A", accent: "柿子橙 #DF7650", detail: "炭褐 #42362C", background: "纸浆白 #FBF8F1" },
    guidance: "Keep kraft visible on 45-65% of each object so the material identity remains stable; use colored paper as constructed panels.",
    contrast: "Outline stitched or layered details with dark brown only when material boundaries would otherwise disappear.",
  }),
  "lime-signal": Object.freeze({
    nameZh: "青柠信号", nameEn: "Lime Signal", summaryZh: "白色主体、荧光青柠和亮黄的高识别配色",
    roles: { primary: "信号青柠 #42E61A", secondary: "亮黄 #FFD91A", tertiary: "冷雾蓝 #DCE6F2", accent: "纯白 #FFFFFF", detail: "墨黑 #171717", background: "纯白 #FFFFFF" },
    guidance: "Use white for most surfaces, lime for the primary state, yellow for a second focal point, and black for structure.",
    contrast: "Keep lime and yellow areas separated by white or black; cap combined saturated area near 25%.",
  }),
});

export const getStyle = (id) => STYLES[id];
export const getPalette = (id) => PALETTES[id];
